---
- hosts: all
  remote_user: root
  tasks: 
    - name: install  Apache
      yum:
       name: httpd
       state: latest
    - service:
        name: httpd
        state: started
    - name: web
      shell: echo hello world > /var/www/html/index.html
